version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: aio_nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - aio_bot
    networks:
      - app-network

  aio_bot:
    build: .
    container_name: aio_bot
    ports:
      - 9000:9000
    command: python main.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
